services:
  postgres:
    image: postgres:15
    container_name: video_pg 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: video_redis 
    restart: always 
    ports:
      - "6379:6379"
  
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: video_api
    env_file:
      - ./api/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5555:5555"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - ./api/uploads:/usr/src/app/uploads
      - ./api/processed:/usr/src/app/processed
    command: ["npm", "start"]
  
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: video_worker
    depends_on:
      - redis
      - postgres
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
      - ./api/uploads:/usr/src/app/uploads
      - ./api/processed:/usr/src/app/processed
    env_file:
      - ./worker/.env
    command: ["npm", "start"]

volumes:
  pgdata: